packages:
  - "apps/*"
  - "apps/services/*"
  - "packages/*"
  - "apps/services/auth/**"
  - "apps/services/mail/*"
  - "apps/services/nutrition/**"
  - "apps/services/gateway/**"
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  esbuild: true
  wasm-pack: true
  workerd: true
minimumReleaseAgeExclude:
  - "@expo/cli@57.0.20"
  - "@expo/env@2.4.3"
  - "@expo/fingerprint@0.20.11"
  - "@expo/metro-config@57.0.12"
  - expo-constants@57.0.16
  - expo-font@57.0.2
  - expo@57.0.18
