/**
 * Error Utilities for Health Worker
 */

/**
 * Error codes for health service
 */
export const HEALTH_ERROR_CODES = {
  // General errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  
  // Readiness errors
  READINESS_NOT_FOUND: 'READINESS_NOT_FOUND',
  READINESS_CALCULATION_FAILED: 'READINESS_CALCULATION_FAILED',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
  
  // Intelligence errors
  INTELLIGENCE_NOT_FOUND: 'INTELLIGENCE_NOT_FOUND',
  INTELLIGENCE_GENERATION_FAILED: 'INTELLIGENCE_GENERATION_FAILED',
  
  // Action errors
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  ACTION_ALREADY_COMPLETED: 'ACTION_ALREADY_COMPLETED',
  INVALID_ACTION_STATUS: 'INVALID_ACTION_STATUS',
  
  // Check-in errors
  CHECKIN_NOT_FOUND: 'CHECKIN_NOT_FOUND',
  CHECKIN_ALREADY_EXISTS: 'CHECKIN_ALREADY_EXISTS',
  CHECKIN_VALIDATION_FAILED: 'CHECKIN_VALIDATION_FAILED',
  
  // Adaptation errors
  ADAPTATION_NOT_FOUND: 'ADAPTATION_NOT_FOUND',
  ADAPTATION_ALREADY_PROCESSED: 'ADAPTATION_ALREADY_PROCESSED',
  INVALID_ADAPTATION_ACTION: 'INVALID_ADAPTATION_ACTION',
  
  // Chart errors
  CHART_NOT_FOUND: 'CHART_NOT_FOUND',
  INVALID_METRIC: 'INVALID_METRIC',
  INVALID_RANGE: 'INVALID_RANGE',
  
  // AI errors
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',
} as const;

export type HealthErrorCode = (typeof HEALTH_ERROR_CODES)[keyof typeof HEALTH_ERROR_CODES];

/**
 * Health service error class
 */
export class HealthError extends Error {
  constructor(
    public code: HealthErrorCode,
    message: string,
    public statusCode: number = 400,
    public details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'HealthError';
  }
}

/**
 * Create health error helper
 */
export function getHealthError(
  code: HealthErrorCode,
  message: string,
  statusCode?: number,
  details?: Record<string, unknown>
): HealthError {
  return new HealthError(code, message, statusCode, details);
}

/**
 * Error mapping for status codes
 */
const STATUS_CODE_MAP: Record<HealthErrorCode, number> = {
  [HEALTH_ERROR_CODES.INTERNAL_ERROR]: 500,
  [HEALTH_ERROR_CODES.VALIDATION_ERROR]: 400,
  [HEALTH_ERROR_CODES.NOT_FOUND]: 404,
  [HEALTH_ERROR_CODES.UNAUTHORIZED]: 401,
  [HEALTH_ERROR_CODES.FORBIDDEN]: 403,
  [HEALTH_ERROR_CODES.RATE_LIMITED]: 429,
  [HEALTH_ERROR_CODES.DATABASE_ERROR]: 500,
  [HEALTH_ERROR_CODES.READINESS_NOT_FOUND]: 404,
  [HEALTH_ERROR_CODES.READINESS_CALCULATION_FAILED]: 500,
  [HEALTH_ERROR_CODES.INSUFFICIENT_DATA]: 400,
  [HEALTH_ERROR_CODES.INTELLIGENCE_NOT_FOUND]: 404,
  [HEALTH_ERROR_CODES.INTELLIGENCE_GENERATION_FAILED]: 500,
  [HEALTH_ERROR_CODES.ACTION_NOT_FOUND]: 404,
  [HEALTH_ERROR_CODES.ACTION_ALREADY_COMPLETED]: 409,
  [HEALTH_ERROR_CODES.INVALID_ACTION_STATUS]: 400,
  [HEALTH_ERROR_CODES.CHECKIN_NOT_FOUND]: 404,
  [HEALTH_ERROR_CODES.CHECKIN_ALREADY_EXISTS]: 409,
  [HEALTH_ERROR_CODES.CHECKIN_VALIDATION_FAILED]: 400,
  [HEALTH_ERROR_CODES.ADAPTATION_NOT_FOUND]: 404,
  [HEALTH_ERROR_CODES.ADAPTATION_ALREADY_PROCESSED]: 409,
  [HEALTH_ERROR_CODES.INVALID_ADAPTATION_ACTION]: 400,
  [HEALTH_ERROR_CODES.CHART_NOT_FOUND]: 404,
  [HEALTH_ERROR_CODES.INVALID_METRIC]: 400,
  [HEALTH_ERROR_CODES.INVALID_RANGE]: 400,
  [HEALTH_ERROR_CODES.AI_GENERATION_FAILED]: 500,
  [HEALTH_ERROR_CODES.AI_QUOTA_EXCEEDED]: 429,
};

/**
 * Get status code for error code
 */
export function getStatusCode(code: HealthErrorCode): number {
  return STATUS_CODE_MAP[code] ?? 400;
}
